### ISSUE TITLE
i want to record my voice and background music...

### ISSUE THREAD

**Issue by davut5** [RLovelett/CFFmpeg.swift#2]

**Comment by RLovelett** [comment]
This is a **_very early days Swift_** wrapper around the FFmpeg C libraries. This library is not anything more than a way to import those structures and functions into Swift. Anything you can do with the FFmpeg C libraries is a goal for CFFmpeg.swift.

All of that is to say, if _you_ already have an existing C library that allows you to "record your voice and background music" and want to port it to Swift then this is a good place to start. To do so is going require a lot of understanding of the [Swift Package Manager](https://github.com/apple/swift-package-manager/) and a lot of understanding about Swift itself.

If you don't already have the C code or have no intention of learning to make those features yourself in Swift than this is not the library for you. And I encourage you to seek the information elsewhere.
